body:
  - type: textarea
    id: body
    attributes:
      label: Body
      value: |
        Steps to reproduce:
        1.
        2.
        3.

        Expected result:
        Actual result:

        ### Additional info

        ```shell
        $ hyprspace -v
        ```
    validations:
      required: true
